version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "derskythe"
    assignees:
      - "derskythe"

  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "derskythe"
    assignees:
      - "derskythe"
