---
name: "Process URL list of dependencies"
description: "Process URL list of dependencies and make env files if necessary"
author: "DerSkythe"
branding:
  icon: 'flag'
  color: 'yellow'

inputs:
  config_file:
    description: 'Path to JSON'
    required: true
  output_prefix:
    description: 'Directory to save env files'
    required: true
  platforms:
    description: 'List of required platforms'
    required: true
  gh_version:
    description: 'Version of GitHub Action Runner'
    required: true
  deps_update_counter:
    description: 'Dependencies update counter for commits new branch'
    required: true
  gh_token:
    description: 'Secret token of GitHub account'
    required: true
outputs:
    counter:
      description: "Updated counter"
      value: ${{ steps.prepare-for-output.outputs.counter }}
    version:
      description: "Latest version of GitHub Action Runner"
      value: ${{ steps.prepare-for-output.outputs.version }}
runs:
  using: composite
  steps:
    - name: Check deps for update
      id: run-check-for-updates
      shell: pwsh
      # return env.FILES_CHANGED, env.NEW_VERSION
      # outputs:
      #   gh_runner_new_version: ${{ steps.run-check-for-updates.outputs.gh_runner_new_version }}
      #   files_changed: ${{ steps.run-check-for-updates.outputs.files_changed }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        CONFIG_FILE: ${{ inputs.config_file }}
        OUTPUT_PREFIX: ${{ inputs.output_prefix }}
        PLATFORMS: ${{ inputs.platforms }}
      run: |
        ./.github/helpers/process-urls.ps1 -JsonFile ${{ env.CONFIG_FILE }} -OutputPrefix ${{ env.OUTPUT_PREFIX }} -Platforms ${{ env.PLATFORMS }} | %{ Write-Output($_) >> $Env:GITHUB_OUTPUT }

    - name: Commit if updated
      id: commit-if-updated
      if: ${{ success() && steps.run-check-for-updates.outputs.files_changed == 1 }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        UPDATE_COUNTER: ${{ inputs.deps_update_counter }}
        NEW_VERSION: ${{ steps.run-check-for-updates.outputs.gh_runner_new_version }}
        BRANCH_NAME: update/deps-${{ inputs.deps_update_counter }}
        LOG_VERSION: ${{ steps.run-check-for-updates.outputs.log_version }}
      shell: bash
      # outputs:
      #   gh_runner_new_version: ${{ steps.run-check-for-updates.outputs.gh_runner_new_version }}
      #   update_counter: ${{ steps.run-check-for-updates.outputs.update_counter }}
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b ${{ env.BRANCH_NAME }}
        git add .
        git commit -m "Dependencies auto update"
        git push --set-upstream origin '${{ env.BRANCH_NAME }}'
        git push
        DEFAULT_BRANCH=(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)
        echo $LOG_VERSION | tr -s ';' "\n" > gh pr create --label 'ci/di' --assignee @me --base "$DEFAULT_BRANCH" --title "Update deps #$UPDATE_COUNTER" --body-file -

#    - name: GitHub runner version was updated
#      if: ${{ steps.run-check-for-updates.outputs.gh_runner_new_version != inputs.gh_version }}
#      env:
#        GITHUB_TOKEN: ${{ inputs.gh_token }}
#        GH_RUNNER_NEW_VERSION: ${{ steps.commit-if-updated.outputs.gh_runner_new_version }}
#      shell: bash
#      run: |
#        gh variable set GH_RUNNER_VERSION -b ${{ env.GH_RUNNER_NEW_VERSION }} -R ${{ github.repository }}

    - name: Dependencies was updated
      id: prepare-for-output
      if: ${{ always() && steps.run-check-for-updates.outputs.files_changed == 1 }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        UPDATE_COUNTER: ${{ inputs.deps_update_counter }}
        NEW_VERSION: ${{ steps.run-check-for-updates.outputs.gh_runner_new_version }}
        CURRENT_VERSION: ${{ inputs.gh_version }}
      shell: pwsh
      run: |
        $Counter = $env:UPDATE_COUNTER + 1
        $NewVersion = (([string]::IsNullOrWhitespace($env:NEW_VERSION)) ? $env:CURRENT_VERSION : $env:NEW_VERSION)
        Write-Output "version=$NewVersion" >> $env:GITHUB_OUTPUT
        Write-Output "counter=$Counter" >> $env:GITHUB_OUTPUT
        gh variable set DEPS_UPDATE_COUNTER -b $Counter -R '${{ github.repository }}'
        gh variable set GH_RUNNER_VERSION -b "$NewVersion" -R '${{ github.repository }}'
