name: "Check for updates"
run-name: "Check for updates «${{ github.ref_name }}» λ${{ github.event_name }}"
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/check-update.yml
      - .github/actions/process-urls/action.yml
      - .github/helpers/process-urls.ps1
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: check-update
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_RUNNER_VERSION: ${{ vars.GH_RUNNER_VERSION }}
      PLATFORMS: 'amd64,arm64'
      ENV_PATH: './variables'
      CONFIG_FILE: './.github/url-list.json'
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v3

      - name: Process URLs
        id: process-urls
        uses: ./.github/actions/process-urls
        with:
          config_file: ${{ env.CONFIG_FILE }}
          output_prefix: ${{ env.ENV_PATH }}
          platforms: ${{ env.PLATFORMS }}
          gh_version: ${{ env.GH_RUNNER_VERSION }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
