name: "Check for updates"
run-name: "Check for updates by @${{ github.ACTOR }}"
on:
  workflow_dispatch:
#  push:
#    paths:
#      - .github/workflows/check-update.yml
#  schedule:
#    - cron: "0 * * * *"

concurrency:
  group: check-update
  cancel-in-progress: false

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      FILES_CHANGED: 0
      NEW_VERSION: ${{ vars.GH_RUNNER_VERSION }}
      GH_RUNNER_VERSION: ${{ vars.GH_RUNNER_VERSION }}
      PLATFORMS: 'amd64,arm64'
      ENV_PATH: './variables'
      CONFIG_FILE: './.github/url-list.json'
      DEPS_UPDATE_COUNTER: ${{ vars.DEPS_UPDATE_COUNTER }}
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v3

      - name: Process URLs
        uses: ./.github/actions/process-urls
        with:
          config_file: ${{ env.CONFIG_FILE }}
          output_prefix: ${{ env.ENV_PATH }}
          platforms: 'linux/amd64,linux/arm64'
          gh_version: ${{ env.GH_RUNNER_VERSION }}
          deps_update_counter: ${{ env.DEPS_UPDATE_COUNTER }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
#EOF
