name: "Runner Deploy DotNet"
run-name: "Deploy DotNet to ${{ inputs.DEPLOY_TARGET }} by @${{ github.ACTOR }}"
on:
#  push:
#    paths-ignore:
#    - Dockerfile.dotnet
#    - .github/workflows/deploy-dotnet.yml
#    branches:
#    - master
#    - develop
#    - update
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy-release:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
      matrix:
        os: [ debian-bullseye, ubuntu-jammy ]
        include:
        -
          os: debian-bullseye
          distro: debian
          codename: 11
        -
          os: ubuntu-jammy
          distro: ubuntu
          codename: jammy
    steps:
    -
      name: Copy Repo Files
      uses: actions/checkout@v3
    -
      name: Set version by default
      run: |
        echo "RELEASE_VERSION=${{ vars.GH_RUNNER_VERSION }}-${{ github.RUN_NUMBER }}.${{ github.RUN_ATTEMPT }}" >> $GITHUB_ENV
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        labels: |
          org.opencontainers.image.name=${{ github.ACTOR }}/${{ vars.RELEASE_IMAGE_NAME }}
          org.opencontainers.image.version=dotnet-${{ env.RELEASE_VERSION }}-${{ matrix.os }}
          org.opencontainers.image.base.name=${{ vars.BASE_IMAGE }}:slim-${{ matrix.os }}-latest
          org.opencontainers.image.revision=${{ github.RUN_NUMBER }}.${{ github.RUN_ATTEMPT }}
          org.opencontainers.image.licenses=MIT
        images: |
          ${{ github.ACTOR }}/${{ vars.RELEASE_IMAGE_NAME }}
          ghcr.io/${{ github.ACTOR }}/${{ vars.RELEASE_IMAGE_NAME }}
        flavor: |
          latest=false
          prefix=
          suffix=
        tags: |
          type=raw,value=dotnet-${{ env.RELEASE_VERSION }}-${{ matrix.os }},enable=true
          type=raw,value=dotnet-${{ env.RELEASE_VERSION }}-${{ matrix.os }}-latest,enable=true
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.dotnet
        provenance: true
        sbom: true
        pull: true
        push: true
        #push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=${{ vars.BASE_IMAGE }}:slim-${{ matrix.os }}-latest
          GH_RUNNER_VERSION=${{ vars.GH_RUNNER_VERSION }}
          DISTRO=${{ matrix.distro }}
          CODENAME=${{ matrix.codename }}
          BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max