name: "RELEASE Create"
run-name: "Release to ${{ inputs.DEPLOY_TARGET }} by @${{ github.ACTOR }}"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    if: ${{ format('refs/tags/{0}', github.REF) && contains(github.REF, github.REF_NAME) }}
    name: Create Release
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        shell: bash
    outputs:
      outvar: ${{ steps.last.outputs.RELEASE_VERSION }}
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Set version by default
      run: |
        echo "RELEASE_VERSION=${{ vars.GH_RUNNER_VERSION }}" >> $GITHUB_ENV
    -
      name: Set release version
      run: |
        if [[ ${{ github.REF }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "RELEASE_VERSION=${{ github.REF_NAME }}" >> $GITHUB_ENV
        fi
        echo "PUBLISH_RELEASE=1" >> $GITHUB_ENV
        echo "::notice::New RELEASE is publishing!"
    -
      name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: ${{ env.PUBLISH_RELEASE == 1 }}
      with:
        tag_name: ${{ github.REF_NAME }}
        name: Release ${{ github.REF_NAME }}
        repository: ${{ github.REPOSITORY }}
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
        target_commitish: ${{ github.SHA }}
        draft: false
        prerelease: false
    -
      name: Set Release version
      id: last
      run: |
        echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" >> $GITHUB_OUTPUT
